PUID & GUID to Dockerfile
ropenttd/docker_openttd pull request #15
Opened 2021-03-25 00:02 UTC by kylepauljohnson

I think this corrects the issue I raised. 

In the interest of full disclosure I can't fully validate this container config on my Synology as I am building it on an ARM M1 Mac, which fails to run on the Synology. Running locally appears to have the desired effect.

2021-03-31 15:27 UTC, duckfullstop commented
(And sorry for the delay on responding, it's been a manic week!)

2021-04-07 08:17 UTC, zogot commented
Also, I dont think 1000:1000 is the correct default UserID and GroupID. 

If i start it up fresh, i seem to get 911 userid and 1000 groupid consistently.

I think perhaps the better approach, to help ensure it, is an explicit set of the UID and GID with ENV values that let us define what those are.

So running useradd -u $PUID and ENV PUID=911.

I can look to making the changings tonight if that would help.

2021-04-07 13:46 UTC, kylepauljohnson commented
@zogot Feel free to run with it. I have been pretty buried as it sounds has @duckfullstop.  Thanks for looking at it.

2023-02-11 15:48 UTC, duckfullstop commented
I'm minded to close this PR for a couple reasons:
1) it's quite old, and the author may not be around anymore
2) the PUID and PGID changes would only take effect during image build, not during execution - we'd still need that change to the entrypoing

I'm happy to merge if both of the above can be disproved (heck, it might also close #17 in the process), but otherwise closing and then throwing it back to the original issue is probably the right move.

2023-02-11 15:48 UTC, duckfullstop requested changes
See comment in issue

2023-02-13 16:20 UTC, kylepauljohnson commented
As much as I would like to complete and solve this, I currently have no time.  I will go ahead and close this.

2023-02-13 16:20 UTC, closed without merging

2023-02-13 17:13 UTC, duckfullstop commented
I'll spend some time thinking how to best fix this when I can - probably continue discussion in #17?